---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for dahyun
    tags: always
    authorized_key:
      user: dahyun
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhOXMtU/RGepcT7wgamk3mFHotdrhnenktrQNZugqaJ ansible take two"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_server
  become: true
  tasks:

  - name: install apache2 and php packages
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache (ubuntu)
    tags: apache,ubuntu,apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: restart apache (ubuntu)
    tags: apache,ubuntu,apache2
    service:
      name: apache2
      state: restarted
  
  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb
    tags: db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"    

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
