---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_server
  become: true
  roles:
    - web_server

- hosts: db_server
  become: true
  roles:
    - db_server

- hosts: file_server
  become: true
  roles:
    - file_server

