- name: install apache and php packages
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache services
  tags: apache,ubuntu,apache2
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes  

- name: restart apache
  tags: apache,apache2,ubuntu
  service:
    name: "{{ apache_service }}"
    state: restarted
 
- name: copy html file for site
  tags: apache,apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
