- name: add ssh key for dahyun
  authorized_key:
    user: dahyun
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhOXMtU/RGepcT7wgamk3mFHotdrhnenktrQNZugqaJ ansible take two"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd 
